
include:
  - system/sys.docker-compose.yaml
  - network/network.docker-compose.yaml
  - database/db.docker-compose.yaml
  - homeassistant/hass.docker-compose.yaml
  - media/media.docker-compose.yaml
  - arr/arr.docker-compose.yaml
